<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_1_Create_and_Verification_Account</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>2f019065-e649-4fb2-ac52-b0e63464798b</testSuiteGuid>
   <testCaseLink>
      <guid>3cf81c8c-590c-4253-b6de-2a2eb1a8095d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/cansu/TC_01_CreateCustomer_OK</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a3419ff-05c5-4849-adae-8ac6ab067e4c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>adb5158e-2eac-446a-a9e8-c278696d1be1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/cansu/TC_02_CreateBillingAccount_OK</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4698b818-4c07-4694-bee4-8f56395825f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0c45fab-8439-4167-ba39-52402db315d8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
